# Site Information
title: Nighthawk Pages 
description: "Class of 2025 - Computer Science and Software Engineering Education"
owner_name: ArnavNadar
github_username: ArnavNadar
github_repo: "arnav_2025" 
baseurl: "/arnav_2025"
future: true

# Theme Configuration
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-compress-images
  - jekyll-minifier

# Navigation
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/projects.md
  - navigation/resources.md
  - README4YML.md

# Social Links
social_links:
  github: "https://github.com/ArnavNadar"
  x: "https://x.com/NighthawkCoding/"
  youtube: "https://www.youtube.com/@nighthawkcodingsociety2868"
  linkedin: "https://www.linkedin.com/in/arnav-nadar/"

# Theme Customization
show_downloads: true
show_header: true
show_footer: true

# SEO Configuration
lang: en-US
locale: en_US
google_analytics: UA-XXXXXXXXX-X  # Replace with your Google Analytics ID

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "ArnavNadar"
      categories: "General"
      tags: []

# Exclude from Processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - .vscode
  - venv
