title: Nighthawk Pages 
description: "Class of 2025"
owner_name: ArnavNadar
github_username: ArnavNadar
github_repo: "arnav_2025" 
baseurl: "/arnav_2025"
future: true

# Theme configuration
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - README4YML.md

# Social links
social_links:
  github: "https://github.com/ArnavNadar"
  x: "https://x.com/NighthawkCoding/"
  youtube: "https://www.youtube.com/@nighthawkcodingsociety2868"

# Theme customization
show_downloads: true
show_header: true
show_footer: true
